# Generated by Django 4.2.19 on 2025-03-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rednotecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='stackoverflowcontent',
            name='content',
        ),
        migrations.AddField(
            model_name='redditcontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rednotecontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stackoverflowcontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
