# Generated by Django 5.1.4 on 2025-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_contentindex_redditcontent_stackoverflowcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RednoteContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('thread_id', models.CharField(max_length=100)),
                ('thread_title', models.TextField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(max_length=150)),
                ('comment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commenter_name', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rednote_content',
                'abstract': False,
                'indexes': [models.Index(fields=['thread_id'], name='littleredbo_thread__94bb99_idx'), models.Index(fields=['comment_id'], name='littleredbo_comment_ad277b_idx'), models.Index(fields=['content_type'], name='littleredbo_content_113110_idx'), models.Index(fields=['created_at'], name='littleredbo_created_b61d04_idx')],
            },
        ),
    ]
