# Generated by Django 4.2.19 on 2025-03-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_redditcontent_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentindex',
            unique_together={('source',)},
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='content',
        ),
    ]
