# Generated by Django 4.2.19 on 2025-03-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_contentindex_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentindex',
            unique_together={('source', 'thread_id')},
        ),
    ]
