# Generated by Django 5.1.4 on 2025-01-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_contentindex_content'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rednotecontent',
            new_name='rednote_con_thread__075376_idx',
            old_name='littleredbo_thread__94bb99_idx',
        ),
        migrations.RenameIndex(
            model_name='rednotecontent',
            new_name='rednote_con_comment_78297c_idx',
            old_name='littleredbo_comment_ad277b_idx',
        ),
        migrations.RenameIndex(
            model_name='rednotecontent',
            new_name='rednote_con_content_0740b6_idx',
            old_name='littleredbo_content_113110_idx',
        ),
        migrations.RenameIndex(
            model_name='rednotecontent',
            new_name='rednote_con_created_e51743_idx',
            old_name='littleredbo_created_b61d04_idx',
        ),
    ]
