# Generated by Django 4.2.19 on 2025-03-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_contentindex_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentindex',
            unique_together=set(),
        ),
    ]
