# Generated by Django 4.2.19 on 2025-03-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_contentindex_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rednotecontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowcontent',
            name='embedding_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
