# Generated by Django 4.2.19 on 2025-03-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_alter_redditcontent_embedding_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditcontent",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rednotecontent",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stackoverflowcontent",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
