# Generated by Django 5.1.4 on 2025-01-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('thread_id', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_index',
            },
        ),
        migrations.CreateModel(
            name='RedditContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('thread_id', models.CharField(max_length=100)),
                ('thread_title', models.TextField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(max_length=150)),
                ('comment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commenter_name', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'reddit_content',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackOverflowContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('thread_id', models.CharField(max_length=100)),
                ('thread_title', models.TextField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(max_length=150)),
                ('comment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commenter_name', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('vote_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stackoverflow_content',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddIndex(
            model_name='redditcontent',
            index=models.Index(fields=['thread_id'], name='reddit_cont_thread__cf72c2_idx'),
        ),
        migrations.AddIndex(
            model_name='redditcontent',
            index=models.Index(fields=['comment_id'], name='reddit_cont_comment_36ffa3_idx'),
        ),
        migrations.AddIndex(
            model_name='redditcontent',
            index=models.Index(fields=['content_type'], name='reddit_cont_content_a3b74e_idx'),
        ),
        migrations.AddIndex(
            model_name='redditcontent',
            index=models.Index(fields=['created_at'], name='reddit_cont_created_ed9371_idx'),
        ),
        migrations.AddIndex(
            model_name='stackoverflowcontent',
            index=models.Index(fields=['thread_id'], name='stackoverfl_thread__ee9648_idx'),
        ),
        migrations.AddIndex(
            model_name='stackoverflowcontent',
            index=models.Index(fields=['comment_id'], name='stackoverfl_comment_acb345_idx'),
        ),
        migrations.AddIndex(
            model_name='stackoverflowcontent',
            index=models.Index(fields=['content_type'], name='stackoverfl_content_240e75_idx'),
        ),
        migrations.AddIndex(
            model_name='stackoverflowcontent',
            index=models.Index(fields=['created_at'], name='stackoverfl_created_a86a48_idx'),
        ),
    ]
