# Generated by Django 5.1.4 on 2025-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rednotecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindex',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
