# Generated by Django 5.1.4 on 2025-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_littleredbo_thread__94bb99_idx_rednote_con_thread__075376_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindex',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='contentindex',
            unique_together={('source', 'content')},
        ),
    ]
