# Generated by Django 5.1.4 on 2025-02-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_contentindex_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='embedding',
        ),
    ]
