# Generated by Django 4.2.19 on 2025-03-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmemory",
            name="platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sessionmemory",
            name="topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
